core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("search.urls", namespace="search")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from .views import SearchFormView, ListResult, DetailResult


app_name = "search"

urlpatterns = [
    path("", SearchFormView.as_view(), name="search_form"),
    path("result/", ListResult.as_view(), name="list_result"),
    path("upload/<str:se>/<str:pk>/", DetailResult.as_view(), name="detail"),
]

search/models.py
from django.db import models


class Tasks(models.Model):
    id = models.CharField(max_length=50, primary_key=True)
    status_code = models.SmallIntegerField()
    status_message = models.CharField(max_length=20)
    time = models.CharField(max_length=20, blank=True, null=True)
    cost = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.id


class DataSearch(models.Model):
    task = models.OneToOneField(
        Tasks, on_delete=models.CASCADE, related_name="task_search"
    )
    api = models.CharField(max_length=20, blank=True, null=True)
    function = models.CharField(max_length=20, blank=True, null=True)
    se = models.CharField(max_length=20)
    se_type = models.CharField(max_length=20, blank=True, null=True)
    language_code = models.CharField(max_length=20, blank=True, null=True)
    location_code = models.CharField(max_length=20, blank=True, null=True)
    keyword = models.CharField(max_length=1000)
    device = models.CharField(max_length=20, blank=True, null=True)
    os = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.task


class Result(models.Model):
    task = models.ForeignKey(
        Tasks, on_delete=models.CASCADE, related_name="task_result"
    )
    type = models.CharField(max_length=20, blank=True, null=True)
    rank_group = models.SmallIntegerField(blank=True, null=True)
    rank_absolute = models.SmallIntegerField(blank=True, null=True)
    domain = models.CharField(max_length=250, blank=True, null=True)
    title = models.CharField(max_length=500, blank=True, null=True)
    description = models.CharField(max_length=2000, blank=True, null=True)
    url = models.URLField(max_length=2000, blank=True, null=True)
    breadcrumb = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.task

search/forms.py
from django import forms

from countries import COUNTRIES, ENGINE


class SearchForm(forms.Form):
    search_engine = forms.ChoiceField(choices=ENGINE, label="Search engine")
    search_region = forms.ChoiceField(choices=COUNTRIES, label="Search engine location")
    keyword = forms.CharField(widget=forms.TextInput, label="Keyword")

    #

search/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, FormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.conf import settings

from .forms import SearchForm
from .client import RestClient
from .models import Tasks, DataSearch, Result

client = RestClient(settings.LOGIN, settings.PASSWORD)


class SearchFormView(FormView):
    template_name = "search/search_form.html"
    form_class = SearchForm
    success_url = reverse_lazy("search:search_form")

    def form_valid(self, form):
        cd = form.cleaned_data
        post_data = dict()
        post_data[len(post_data)] = dict(
            language_code="en",
            location_code=cd["search_region"],
            keyword=cd["keyword"],
        )
        response = client.post(
            f"/v3/serp/{cd['search_engine']}/organic/task_post", post_data
        )
        if (
            response["status_code"] == 20000
            and response["tasks"][0]["status_code"] == 20100
        ):
            res = response["tasks"][0]
            task = Tasks.objects.create(
                id=res["id"],
                status_code=res["status_code"],
                status_message=res["status_message"],
                time=res["time"],
                cost=res["cost"],
            )
            data = DataSearch.objects.create(task=task, **res["data"])
            task.save()
            data.save()
            messages.success(
                self.request,
                'The task has been created. To view the status of a task, click the "Task Status" button',
            )
        else:
            messages.error(
                self.request,
                "error. Code: %d Message: %s"
                % (response["status_code"], response["status_message"]),
            )
        return HttpResponseRedirect(self.get_success_url())


class ListResult(ListView):
    template_name = "search/list_result.html"
    paginate_by = 10
    context_object_name = "results"

    def get_queryset(self):
        results = Tasks.objects.all().select_related()
        tasks_ = [_ for _ in results if _.status_message=="Task Created."]
        for task_ in tasks_:
            response = client.get(f"/v3/serp/{task_.task_search.se}/organic/tasks_ready")
            if response["status_code"] == 20000:
                for task in response["tasks"]:
                    if task["result"]:
                        for result in task["result"]:
                            Tasks.objects.filter(id=result["id"]).update(
                                status_code=task["status_code"],
                                status_message=task["status_message"],
                            )
            else:
                messages.error(
                    self.request,
                    "error. Code: %d Message: %s"
                    % (response["status_code"], response["status_message"]),
                )
        results = Tasks.objects.all().select_related() if tasks_ else results
        return results


class DetailResult(ListView):
    template_name = "search/detail_result.html"
    context_object_name = "results"

    def get_queryset(self):
        pk = self.kwargs["pk"]
        engine = self.kwargs["se"]
        task_id = Tasks.objects.filter(id=pk).first()
        results = []
        if task_id.status_message == "Downloaded":
            results = Result.objects.filter(task=task_id)
            return results
        response = client.get(f"/v3/serp/{engine}/organic/task_get/regular/{pk}")
        if response["status_code"] == 20000:
            task = response["tasks"][0]
            if task["result"] and (len(task["result"]) > 0):
                for result in task["result"]:
                    res = []
                    if result["items"]:
                        for item in result["items"]:
                            item["task"] = task_id
                            res.append(item)
                        Result.objects.bulk_create([Result(**i) for i in res])
                        Tasks.objects.filter(id=pk).update(status_message="Downloaded")
                    else:
                        Tasks.objects.filter(id=pk).update(
                            status_message="No Search Results."
                        )
                        messages.error(self.request, "No Search Results.")
                        return

            results = Result.objects.filter(task=task_id)
        else:
            messages.error(
                self.request,
                "error. Code: %d Message: %s"
                % (response["status_code"], response["status_message"]),
            )
        return results

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Data for SEO</title>
</head>
<body>
<div class="container_fluid">
    {% for message in messages %}
    <div class="offset-3 col-sm-5 alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

templates/search/detail_result.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <h1>Detail result</h1>
    <div class="row">
        <div class="col-sm-1">
            <p> <a href="{% url 'search:search_form' %}" class="btn btn-primary">New task</a></p>
            <p><a href="{% url 'search:list_result' %}" class="btn btn-primary">Task status</a></p>
        </div>
        <div class="col-sm-8 offset-1">
            {% for result in results %}
            <p><span class="text-muted">Group rank in SERP:</span> {{ result.rank_group }}<br>
                <span class="text-muted">Absolute rank in SERP:</span> {{ result.rank_absolute }}<br>
                <span class="text-muted">Domain in SERP:</span> {{ result.domain }}<br>
                <span class="text-muted">Title of the results element in SERP:</span> {{ result.title }}<br>
                <span class="text-muted">Description of the results element in SERP:</span> {{ result.description }}<br>
                <span class="text-muted">Relevant URL in SERP:</span> <a href="{{ result.url }}">{{ result.url }}</a><br>
                <span class="text-muted">Breadcrumb in SERP:</span> {{ result.breadcrumb }}
            </p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/search/list_result.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <h1>Tasks status</h1>
    <div class="row">
        <div class="col-sm-2">
            <a href="{% url 'search:search_form' %}" class="btn btn-primary">New task</a>
        </div>
        <div class="col-sm-8 offset-3">
            {% for result in results %}
            <p><span class="text-muted">Task:</span> {{ result.id }}<br>
                <span class="text-muted">Status the task:</span> {{ result.status_message }}<br>
                <span class="text-muted">Search engine:</span> {{ result.task_search.se }}<br>
                <span class="text-muted">Language_code:</span> {{ result.task_search.language_code }}<br>
                <span class="text-muted">Location_code:</span> {{ result.task_search.location_code }}<br>
                <span class="text-muted">Keyword:</span> {{ result.task_search.keyword }}<br>
                {% if result.status_message == 'Ok.' %}
                <a href="{% url 'search:detail' se=result.task_search.se pk=result.id %}" class="btn btn-primary">Load Result</a>
                {% elif result.status_message == 'Downloaded' %}
                <a href="{% url 'search:detail' se=result.task_search.se pk=result.id %}" class="btn btn-primary">View result</a>
                {% endif %}</p>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/search/search_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <h1>New task</h1>
    <div class="row">
        <div class="col-sm-2">
            <a href="{% url 'search:list_result' %}" class="btn btn-primary">Task status</a>
        </div>
        <div class="col-sm-6 offset-1">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type="submit">Create task</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}